buffer:
  capacity: 1000000
logger:
  agent_name: SAC
  enabled: true
  env_name: ConstantRewardEnv
  experiment_name: sac-hparam-search-trial-0
  flush_secs: 10
  log_dir: hparam_search/hparam_runs/sac-hparam-search-ConstantRewardEnv_3/trial_0
  log_episode_stats: true
  log_q_values: true
  run_name: sac
  save_model:
    enabled: false
    path: null
  timestamp_format: '%Y_%m_%d-%H_%M_%S'
  use_timestamp: true
policy_net:
  action_scale: 1.0
  hidden_layers_act: relu
  hidden_sizes:
  - 256
  - 256
  log_std_max: 2
  log_std_min: -20
  output_activation: identity
q_net:
  hidden_layers_act: relu
  hidden_sizes:
  - 256
  - 256
  output_activation: identity
sac:
  actor_lr: 0.0003
  alpha: 0.1
  alpha_lr: 0.0035061599889844117
  auto_entropy_tuning: false
  critic_lr: 0.0003
  gamma: 0.99
  tau: 0.005
train:
  batch_size: 256
  device: cuda
  gradient_steps_per_update: 1
  num_episodes: 2000
  seed: 0
  warming_steps: 1000
